// Generated by npm run db:types from committed migrations; do not edit.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      ai_usage_reservations: {
        Row: {
          attempt_id: string
          class_id: string
          created_at: string
          id: string
          operation: string
          student_id: string
          units: number
        }
        Insert: {
          attempt_id: string
          class_id: string
          created_at?: string
          id?: string
          operation: string
          student_id: string
          units: number
        }
        Update: {
          attempt_id?: string
          class_id?: string
          created_at?: string
          id?: string
          operation?: string
          student_id?: string
          units?: number
        }
        Relationships: [
          {
            foreignKeyName: "ai_usage_reservations_attempt_id_fkey"
            columns: ["attempt_id"]
            isOneToOne: false
            referencedRelation: "attempts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ai_usage_reservations_class_id_fkey"
            columns: ["class_id"]
            isOneToOne: false
            referencedRelation: "classes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "ai_usage_reservations_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      assessment_assignments: {
        Row: {
          archived_at: string | null
          assessment_id: string
          class_id: string
          created_at: string
          due_at: string | null
          id: string
          opens_at: string | null
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          assessment_id: string
          class_id: string
          created_at?: string
          due_at?: string | null
          id?: string
          opens_at?: string | null
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          assessment_id?: string
          class_id?: string
          created_at?: string
          due_at?: string | null
          id?: string
          opens_at?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "assessment_assignments_assessment_id_fkey"
            columns: ["assessment_id"]
            isOneToOne: false
            referencedRelation: "assessments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "assessment_assignments_class_id_fkey"
            columns: ["class_id"]
            isOneToOne: false
            referencedRelation: "classes"
            referencedColumns: ["id"]
          },
        ]
      }
      assessment_versions: {
        Row: {
          assessment_id: string
          created_at: string
          definition: Json
          id: string
          legacy_capture: boolean
        }
        Insert: {
          assessment_id: string
          created_at?: string
          definition: Json
          id?: string
          legacy_capture?: boolean
        }
        Update: {
          assessment_id?: string
          created_at?: string
          definition?: Json
          id?: string
          legacy_capture?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "assessment_versions_assessment_id_fkey"
            columns: ["assessment_id"]
            isOneToOne: false
            referencedRelation: "assessments"
            referencedColumns: ["id"]
          },
        ]
      }
      assessments: {
        Row: {
          archived_at: string | null
          config: Json
          created_at: string
          created_by: string | null
          expected_answer: string | null
          id: string
          prompt: string
          rubric: Json
          title: string
          type: string
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          config?: Json
          created_at?: string
          created_by?: string | null
          expected_answer?: string | null
          id?: string
          prompt: string
          rubric?: Json
          title: string
          type: string
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          config?: Json
          created_at?: string
          created_by?: string | null
          expected_answer?: string | null
          id?: string
          prompt?: string
          rubric?: Json
          title?: string
          type?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "assessments_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      attempt_artifacts: {
        Row: {
          attempt_id: string
          bucket: string
          byte_size: number
          cleanup_at: string | null
          cleanup_attempts: number
          cleanup_claimed_at: string | null
          cleanup_error: string | null
          content_sha256: string | null
          created_at: string
          frozen_at: string | null
          id: string
          kind: string
          mime_type: string
          openai_file_id: string | null
          original_filename: string
          provider_cleanup_at: string | null
          simulation_html_viewport_height: number | null
          simulation_html_viewport_width: number | null
          source_description_sha256: string | null
          storage_key: string
          student_id: string
          upload_state: string
        }
        Insert: {
          attempt_id: string
          bucket: string
          byte_size?: number
          cleanup_at?: string | null
          cleanup_attempts?: number
          cleanup_claimed_at?: string | null
          cleanup_error?: string | null
          content_sha256?: string | null
          created_at?: string
          frozen_at?: string | null
          id?: string
          kind: string
          mime_type: string
          openai_file_id?: string | null
          original_filename?: string
          provider_cleanup_at?: string | null
          simulation_html_viewport_height?: number | null
          simulation_html_viewport_width?: number | null
          source_description_sha256?: string | null
          storage_key: string
          student_id: string
          upload_state?: string
        }
        Update: {
          attempt_id?: string
          bucket?: string
          byte_size?: number
          cleanup_at?: string | null
          cleanup_attempts?: number
          cleanup_claimed_at?: string | null
          cleanup_error?: string | null
          content_sha256?: string | null
          created_at?: string
          frozen_at?: string | null
          id?: string
          kind?: string
          mime_type?: string
          openai_file_id?: string | null
          original_filename?: string
          provider_cleanup_at?: string | null
          simulation_html_viewport_height?: number | null
          simulation_html_viewport_width?: number | null
          source_description_sha256?: string | null
          storage_key?: string
          student_id?: string
          upload_state?: string
        }
        Relationships: [
          {
            foreignKeyName: "attempt_artifacts_attempt_id_fkey"
            columns: ["attempt_id"]
            isOneToOne: false
            referencedRelation: "attempts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attempt_artifacts_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      attempt_audit_logs: {
        Row: {
          attempt_id: string
          created_at: string
          error: string | null
          id: string
          model: string
          provider: string
          raw_response: Json | null
          request_summary: Json | null
          route: string
        }
        Insert: {
          attempt_id: string
          created_at?: string
          error?: string | null
          id?: string
          model: string
          provider: string
          raw_response?: Json | null
          request_summary?: Json | null
          route: string
        }
        Update: {
          attempt_id?: string
          created_at?: string
          error?: string | null
          id?: string
          model?: string
          provider?: string
          raw_response?: Json | null
          request_summary?: Json | null
          route?: string
        }
        Relationships: [
          {
            foreignKeyName: "attempt_audit_logs_attempt_id_fkey"
            columns: ["attempt_id"]
            isOneToOne: false
            referencedRelation: "attempts"
            referencedColumns: ["id"]
          },
        ]
      }
      attempt_realtime_events: {
        Row: {
          attempt_id: string
          created_at: string
          event_type: string
          id: string
          metadata: Json
          occurred_at: string
          role: string | null
          sequence: number
          session_id: string
          student_id: string
          text: string | null
        }
        Insert: {
          attempt_id: string
          created_at?: string
          event_type: string
          id?: string
          metadata?: Json
          occurred_at?: string
          role?: string | null
          sequence: number
          session_id: string
          student_id: string
          text?: string | null
        }
        Update: {
          attempt_id?: string
          created_at?: string
          event_type?: string
          id?: string
          metadata?: Json
          occurred_at?: string
          role?: string | null
          sequence?: number
          session_id?: string
          student_id?: string
          text?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "attempt_realtime_events_attempt_id_fkey"
            columns: ["attempt_id"]
            isOneToOne: false
            referencedRelation: "attempts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attempt_realtime_events_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "attempt_realtime_sessions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attempt_realtime_events_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      attempt_realtime_sessions: {
        Row: {
          attempt_id: string
          continuity_diagnostics: Json
          created_at: string
          ended_at: string | null
          expires_at: string | null
          finalize_error: string | null
          finalized_at: string | null
          finalized_attempt_id: string | null
          finalized_feedback: Json | null
          finalized_score: number | null
          finalized_transcript: string | null
          id: string
          model: string
          provider: string
          provider_session_id: string | null
          started_at: string
          status: string
          student_id: string
          updated_at: string
        }
        Insert: {
          attempt_id: string
          continuity_diagnostics?: Json
          created_at?: string
          ended_at?: string | null
          expires_at?: string | null
          finalize_error?: string | null
          finalized_at?: string | null
          finalized_attempt_id?: string | null
          finalized_feedback?: Json | null
          finalized_score?: number | null
          finalized_transcript?: string | null
          id?: string
          model: string
          provider?: string
          provider_session_id?: string | null
          started_at?: string
          status?: string
          student_id: string
          updated_at?: string
        }
        Update: {
          attempt_id?: string
          continuity_diagnostics?: Json
          created_at?: string
          ended_at?: string | null
          expires_at?: string | null
          finalize_error?: string | null
          finalized_at?: string | null
          finalized_attempt_id?: string | null
          finalized_feedback?: Json | null
          finalized_score?: number | null
          finalized_transcript?: string | null
          id?: string
          model?: string
          provider?: string
          provider_session_id?: string | null
          started_at?: string
          status?: string
          student_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "attempt_realtime_sessions_attempt_id_fkey"
            columns: ["attempt_id"]
            isOneToOne: false
            referencedRelation: "attempts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attempt_realtime_sessions_finalized_attempt_id_fkey"
            columns: ["finalized_attempt_id"]
            isOneToOne: false
            referencedRelation: "attempts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attempt_realtime_sessions_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      attempts: {
        Row: {
          assessment_id: string
          assessment_version_id: string
          assignment_id: string | null
          created_at: string
          due_at_snapshot: string | null
          grading_metadata: Json | null
          id: string
          ocr_text: string | null
          provisional_feedback: Json | null
          provisional_score: number | null
          simulation_description: string | null
          simulation_spec: Json | null
          status: string
          student_id: string
          submitted_after_due: boolean
          submitted_at: string | null
          transcript: string | null
          updated_at: string
        }
        Insert: {
          assessment_id: string
          assessment_version_id: string
          assignment_id?: string | null
          created_at?: string
          due_at_snapshot?: string | null
          grading_metadata?: Json | null
          id?: string
          ocr_text?: string | null
          provisional_feedback?: Json | null
          provisional_score?: number | null
          simulation_description?: string | null
          simulation_spec?: Json | null
          status?: string
          student_id: string
          submitted_after_due?: boolean
          submitted_at?: string | null
          transcript?: string | null
          updated_at?: string
        }
        Update: {
          assessment_id?: string
          assessment_version_id?: string
          assignment_id?: string | null
          created_at?: string
          due_at_snapshot?: string | null
          grading_metadata?: Json | null
          id?: string
          ocr_text?: string | null
          provisional_feedback?: Json | null
          provisional_score?: number | null
          simulation_description?: string | null
          simulation_spec?: Json | null
          status?: string
          student_id?: string
          submitted_after_due?: boolean
          submitted_at?: string | null
          transcript?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "attempts_assessment_id_fkey"
            columns: ["assessment_id"]
            isOneToOne: false
            referencedRelation: "assessments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attempts_assessment_version_id_fkey"
            columns: ["assessment_version_id"]
            isOneToOne: false
            referencedRelation: "assessment_versions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attempts_assignment_id_fkey"
            columns: ["assignment_id"]
            isOneToOne: false
            referencedRelation: "assessment_assignments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attempts_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      class_memberships: {
        Row: {
          class_id: string
          created_at: string
          display_name: string
          id: string
          roster_student_id: string | null
          student_id: string
        }
        Insert: {
          class_id: string
          created_at?: string
          display_name?: string
          id?: string
          roster_student_id?: string | null
          student_id: string
        }
        Update: {
          class_id?: string
          created_at?: string
          display_name?: string
          id?: string
          roster_student_id?: string | null
          student_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "class_memberships_class_id_fkey"
            columns: ["class_id"]
            isOneToOne: false
            referencedRelation: "classes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "class_memberships_roster_student_id_fkey"
            columns: ["roster_student_id"]
            isOneToOne: false
            referencedRelation: "roster_students"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "class_memberships_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      classes: {
        Row: {
          archived_at: string | null
          code: string
          created_at: string
          id: string
          name: string
          section: string | null
          teacher_id: string | null
          term: string | null
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          code: string
          created_at?: string
          id?: string
          name: string
          section?: string | null
          teacher_id?: string | null
          term?: string | null
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          code?: string
          created_at?: string
          id?: string
          name?: string
          section?: string | null
          teacher_id?: string | null
          term?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "classes_teacher_id_fkey"
            columns: ["teacher_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      grade_exports: {
        Row: {
          assignment_ids: string[]
          column_count: number
          column_labels: Json
          column_order: string[]
          course_id: string
          created_at: string
          format: string
          id: string
          include_unpublished: boolean
          missing_mode: string
          row_count: number
          teacher_id: string
        }
        Insert: {
          assignment_ids?: string[]
          column_count?: number
          column_labels?: Json
          column_order?: string[]
          course_id: string
          created_at?: string
          format: string
          id?: string
          include_unpublished?: boolean
          missing_mode: string
          row_count?: number
          teacher_id: string
        }
        Update: {
          assignment_ids?: string[]
          column_count?: number
          column_labels?: Json
          column_order?: string[]
          course_id?: string
          created_at?: string
          format?: string
          id?: string
          include_unpublished?: boolean
          missing_mode?: string
          row_count?: number
          teacher_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "grade_exports_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "classes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "grade_exports_teacher_id_fkey"
            columns: ["teacher_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      gradebook_entries: {
        Row: {
          approved_attempt_id: string | null
          approved_feedback: Json | null
          approved_score: number | null
          assignment_id: string
          created_at: string
          id: string
          missing: boolean
          published_at: string | null
          roster_student_id: string
          teacher_override_note: string | null
          teacher_override_score: number | null
          updated_at: string
        }
        Insert: {
          approved_attempt_id?: string | null
          approved_feedback?: Json | null
          approved_score?: number | null
          assignment_id: string
          created_at?: string
          id?: string
          missing?: boolean
          published_at?: string | null
          roster_student_id: string
          teacher_override_note?: string | null
          teacher_override_score?: number | null
          updated_at?: string
        }
        Update: {
          approved_attempt_id?: string | null
          approved_feedback?: Json | null
          approved_score?: number | null
          assignment_id?: string
          created_at?: string
          id?: string
          missing?: boolean
          published_at?: string | null
          roster_student_id?: string
          teacher_override_note?: string | null
          teacher_override_score?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "gradebook_entries_approved_attempt_id_fkey"
            columns: ["approved_attempt_id"]
            isOneToOne: false
            referencedRelation: "attempts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "gradebook_entries_assignment_id_fkey"
            columns: ["assignment_id"]
            isOneToOne: false
            referencedRelation: "assessment_assignments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "gradebook_entries_roster_student_id_fkey"
            columns: ["roster_student_id"]
            isOneToOne: false
            referencedRelation: "roster_students"
            referencedColumns: ["id"]
          },
        ]
      }
      gradebook_history: {
        Row: {
          course_owner_id: string
          created_at: string
          entry_id: string
          id: string
          new_value: Json
          previous_value: Json
        }
        Insert: {
          course_owner_id: string
          created_at?: string
          entry_id: string
          id?: string
          new_value: Json
          previous_value: Json
        }
        Update: {
          course_owner_id?: string
          created_at?: string
          entry_id?: string
          id?: string
          new_value?: Json
          previous_value?: Json
        }
        Relationships: []
      }
      profiles: {
        Row: {
          created_at: string
          display_name: string
          email: string | null
          id: string
          role: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          display_name?: string
          email?: string | null
          id: string
          role?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          display_name?: string
          email?: string | null
          id?: string
          role?: string
          updated_at?: string
        }
        Relationships: []
      }
      roster_students: {
        Row: {
          claimed_at: string | null
          claimed_by: string | null
          class_id: string
          created_at: string
          deactivated_at: string | null
          display_name: string
          email: string | null
          email_normalized: string | null
          id: string
          section: string | null
          student_identifier: string | null
          updated_at: string
        }
        Insert: {
          claimed_at?: string | null
          claimed_by?: string | null
          class_id: string
          created_at?: string
          deactivated_at?: string | null
          display_name: string
          email?: string | null
          email_normalized?: string | null
          id?: string
          section?: string | null
          student_identifier?: string | null
          updated_at?: string
        }
        Update: {
          claimed_at?: string | null
          claimed_by?: string | null
          class_id?: string
          created_at?: string
          deactivated_at?: string | null
          display_name?: string
          email?: string | null
          email_normalized?: string | null
          id?: string
          section?: string | null
          student_identifier?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "roster_students_claimed_by_fkey"
            columns: ["claimed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "roster_students_class_id_fkey"
            columns: ["class_id"]
            isOneToOne: false
            referencedRelation: "classes"
            referencedColumns: ["id"]
          },
        ]
      }
      simulation_generation_jobs: {
        Row: {
          attempt_id: string
          cancelled_at: string | null
          completed_at: string | null
          created_at: string
          error_message: string | null
          expires_at: string
          id: string
          idempotency_key: string | null
          input_html_artifact_id: string | null
          model_used: string | null
          operation: string
          provider: string
          provider_response_id: string | null
          provider_status: string | null
          reasoning_effort: string
          requested_model: string
          result_artifact_id: string | null
          sketch_artifact_id: string
          source_description_sha256: string
          status: string
          student_id: string
          updated_at: string
        }
        Insert: {
          attempt_id: string
          cancelled_at?: string | null
          completed_at?: string | null
          created_at?: string
          error_message?: string | null
          expires_at: string
          id?: string
          idempotency_key?: string | null
          input_html_artifact_id?: string | null
          model_used?: string | null
          operation: string
          provider?: string
          provider_response_id?: string | null
          provider_status?: string | null
          reasoning_effort?: string
          requested_model: string
          result_artifact_id?: string | null
          sketch_artifact_id: string
          source_description_sha256: string
          status: string
          student_id: string
          updated_at?: string
        }
        Update: {
          attempt_id?: string
          cancelled_at?: string | null
          completed_at?: string | null
          created_at?: string
          error_message?: string | null
          expires_at?: string
          id?: string
          idempotency_key?: string | null
          input_html_artifact_id?: string | null
          model_used?: string | null
          operation?: string
          provider?: string
          provider_response_id?: string | null
          provider_status?: string | null
          reasoning_effort?: string
          requested_model?: string
          result_artifact_id?: string | null
          sketch_artifact_id?: string
          source_description_sha256?: string
          status?: string
          student_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "simulation_generation_jobs_attempt_id_fkey"
            columns: ["attempt_id"]
            isOneToOne: false
            referencedRelation: "attempts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "simulation_generation_jobs_input_html_artifact_id_fkey"
            columns: ["input_html_artifact_id"]
            isOneToOne: false
            referencedRelation: "attempt_artifacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "simulation_generation_jobs_result_artifact_id_fkey"
            columns: ["result_artifact_id"]
            isOneToOne: false
            referencedRelation: "attempt_artifacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "simulation_generation_jobs_sketch_artifact_id_fkey"
            columns: ["sketch_artifact_id"]
            isOneToOne: false
            referencedRelation: "attempt_artifacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "simulation_generation_jobs_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      student_access_codes: {
        Row: {
          claimed_at: string | null
          claimed_by: string | null
          class_id: string
          created_at: string
          id: string
          pin_hash: string
          roster_student_id: string | null
          student_label: string | null
        }
        Insert: {
          claimed_at?: string | null
          claimed_by?: string | null
          class_id: string
          created_at?: string
          id?: string
          pin_hash: string
          roster_student_id?: string | null
          student_label?: string | null
        }
        Update: {
          claimed_at?: string | null
          claimed_by?: string | null
          class_id?: string
          created_at?: string
          id?: string
          pin_hash?: string
          roster_student_id?: string | null
          student_label?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "student_access_codes_claimed_by_fkey"
            columns: ["claimed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "student_access_codes_class_id_fkey"
            columns: ["class_id"]
            isOneToOne: false
            referencedRelation: "classes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "student_access_codes_roster_student_id_fkey"
            columns: ["roster_student_id"]
            isOneToOne: false
            referencedRelation: "roster_students"
            referencedColumns: ["id"]
          },
        ]
      }
      submission_artifacts: {
        Row: {
          artifact_id: string
          attempt_id: string
          content_sha256: string | null
        }
        Insert: {
          artifact_id: string
          attempt_id: string
          content_sha256?: string | null
        }
        Update: {
          artifact_id?: string
          attempt_id?: string
          content_sha256?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "submission_artifacts_artifact_id_fkey"
            columns: ["artifact_id"]
            isOneToOne: false
            referencedRelation: "attempt_artifacts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "submission_artifacts_attempt_id_fkey"
            columns: ["attempt_id"]
            isOneToOne: false
            referencedRelation: "attempts"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      claim_artifact_cleanup: {
        Args: { p_artifact_id: string }
        Returns: boolean
      }
      claim_attempt_submission: {
        Args: {
          p_artifact_ids?: string[]
          p_attempt_id: string
          p_description_sha256?: string
          p_simulation_description?: string
          p_submitted_at: string
          p_user_id: string
        }
        Returns: {
          assignment_due_at: string
          assignment_id: string
          attempt_id: string
          claim_status: string
          current_attempt_status: string
          submitted_after_due: boolean
          submitted_at: string
        }[]
      }
      claim_first_teacher: {
        Args: { p_display_name: string; p_user_id: string }
        Returns: {
          display_name: string
          id: string
        }[]
      }
      claim_realtime_submission: {
        Args: { p_session_id: string; p_transcript: string; p_user_id: string }
        Returns: undefined
      }
      claim_student_google_login: {
        Args: {
          p_class_code: string
          p_email: string
          p_pin_hash: string
          p_user_id: string
        }
        Returns: {
          claim_status: string
          class_code: string
          class_id: string
          class_name: string
          display_name: string
          previous_user_id: string
          roster_student_id: string
        }[]
      }
      complete_artifact_upload: {
        Args: { p_artifact_id: string; p_sha256: string; p_user_id: string }
        Returns: undefined
      }
      consume_ai_budget: {
        Args: {
          p_attempt_id: string
          p_operation: string
          p_units: number
          p_user_id: string
        }
        Returns: string
      }
      enroll_student_by_email: { Args: { p_user_id: string }; Returns: Json }
      import_course_roster: {
        Args: { p_course_id: string; p_rows: Json; p_teacher_id: string }
        Returns: number
      }
      reconcile_course_gradebook: {
        Args: { p_course_id: string; p_teacher_id: string }
        Returns: Json
      }
      record_artifact_cleanup: {
        Args: { p_artifact_id: string; p_changes: Json }
        Returns: undefined
      }
      recover_stale_assessment_work: { Args: never; Returns: undefined }
      reserve_simulation_job: {
        Args: {
          p_attempt_id: string
          p_input: Json
          p_key: string
          p_user_id: string
        }
        Returns: Json
      }
      save_realtime_grade: {
        Args: {
          p_diagnostics: Json
          p_feedback: Json
          p_metadata: Json
          p_session_id: string
          p_transcript: string
          p_user_id: string
        }
        Returns: undefined
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const

