import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

export const CLI_VERSION = '2.81.3';
const root = fileURLToPath(new URL('../', import.meta.url));
const npx = process.platform === 'win32' ? 'npx.cmd' : 'npx';
export function cli(args, options = {}) {
  return execFileSync(npx, ['--yes', `supabase@${CLI_VERSION}`, ...args], {
    cwd: root, encoding: 'utf8', maxBuffer: 8 * 1024 * 1024,
    stdio: ['ignore', 'pipe', 'inherit'], ...options
  });
}

export function localCredentials() {
  // Read only this checkout's local containers; never use a linked project.
  const values = JSON.parse(cli(['status', '--output', 'json']));
  for (const key of ['API_URL', 'DB_URL']) {
    if (!values[key] || !['127.0.0.1', 'localhost', '[::1]'].includes(new URL(values[key]).hostname)) {
      throw new Error('Integration tests require a disposable localhost Supabase stack.');
    }
  }
  if (!values.ANON_KEY || !values.SERVICE_ROLE_KEY) throw new Error('Local Supabase credentials are unavailable.');
  return values;
}

const command = process.argv[2];
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  if (command === 'start') {
    cli(['start', '--exclude', 'realtime,imgproxy,studio,edge-runtime,logflare,vector,supavisor,mailpit'], { stdio: ['ignore', 'ignore', 'inherit'] });
  } else if (command === 'stop') {
    cli(['stop', '--no-backup'], { stdio: ['ignore', 'ignore', 'inherit'] });
  } else if (command === 'types' || command === 'check-types') {
    localCredentials();
    const output = cli(['gen', 'types', '--local', '--schema', 'public']);
    if (!output.includes('export type Database') || !output.includes('claim_realtime_submission')) {
      throw new Error('Generated types do not include the current assessment schema.');
    }
    const target = new URL('../worker/src/lib/database.generated.ts', import.meta.url);
    const generated = '// Generated by npm run db:types from committed migrations; do not edit.\n' + output;
    if (command === 'types') writeFileSync(target, generated);
    else if (readFileSync(target, 'utf8') !== generated) throw new Error('Database types are stale. Run npm run db:types and commit the result.');
  } else {
    throw new Error('Usage: node scripts/supabase-local.mjs start|stop|types|check-types');
  }
}
